<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="8" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="155" started-at="2022-11-17T15:40:13Z" finished-at="2022-11-17T15:40:14Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="155" started-at="2022-11-17T15:40:13Z" finished-at="2022-11-17T15:40:14Z">
      <class name="org.test.FailedTest">
        <test-method status="PASS" signature="tc1()[pri:0, instance:org.test.FailedTest@51efea79]" name="tc1" duration-ms="0" started-at="2022-11-17T15:40:14Z" finished-at="2022-11-17T15:40:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="FAIL" signature="tc2()[pri:0, instance:org.test.FailedTest@51efea79]" name="tc2" duration-ms="0" started-at="2022-11-17T15:40:14Z" finished-at="2022-11-17T15:40:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.test.FailedTest.tc2(FailedTest.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.test.FailedTest@51efea79]" name="tc3" duration-ms="0" started-at="2022-11-17T15:40:14Z" finished-at="2022-11-17T15:40:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="tc4()[pri:0, instance:org.test.FailedTest@51efea79]" name="tc4" duration-ms="3" started-at="2022-11-17T15:40:14Z" finished-at="2022-11-17T15:40:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc4 -->
      </class> <!-- org.test.FailedTest -->
      <class name="org.test.Failestest2">
        <test-method status="PASS" signature="tc10()[pri:0, instance:org.test.Failestest2@6d00a15d]" name="tc10" duration-ms="11" started-at="2022-11-17T15:40:13Z" finished-at="2022-11-17T15:40:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc10 -->
        <test-method status="PASS" signature="tc20()[pri:0, instance:org.test.Failestest2@6d00a15d]" name="tc20" duration-ms="0" started-at="2022-11-17T15:40:14Z" finished-at="2022-11-17T15:40:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc20 -->
        <test-method status="PASS" signature="tc30()[pri:0, instance:org.test.Failestest2@6d00a15d]" name="tc30" duration-ms="0" started-at="2022-11-17T15:40:14Z" finished-at="2022-11-17T15:40:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc30 -->
        <test-method status="PASS" signature="tc40()[pri:0, instance:org.test.Failestest2@6d00a15d]" name="tc40" duration-ms="0" started-at="2022-11-17T15:40:14Z" finished-at="2022-11-17T15:40:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc40 -->
      </class> <!-- org.test.Failestest2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
